FROM zenoss/centos-base:%CENTOS_BASE_TAG%
MAINTAINER Zenoss <dev@zenoss.com>

RUN yum install epel-release -y \
    && yum -y groupinstall "Development Tools" \
    && yum -y install \
       dmidecode \
       libffi-devel \
       libsmi \
       libxml2-devel \
       libxslt-devel \
       mariadb-devel \
       maven \
       mysql-devel \
       net-snmp-libs \
       openldap-devel \
       openssl-devel \
       patch \
       pcre-devel \
       python-devel \
       python-pip \
       rsync \
       sudo \
       sysstat \
       tar \
       unzip \
       wget \
       which \
       yum-plugin-ovl \
    && yum erase epel-release -y \
    && /sbin/scrub.sh

RUN sed -i 's/requiretty/!requiretty/' /etc/sudoers

RUN pip install --upgrade pip wheel virtualenv setuptools

RUN groupadd -f -g %GID% build
RUN useradd -d /home/build -m -s /bin/bash -u %UID% -g %GID% build
RUN echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
USER build
