FROM zenoss/centos-base:%CENTOS_BASE_TAG%
MAINTAINER Zenoss <dev@zenoss.com>

RUN yum install epel-release -y \
    && yum -y groupinstall "Development Tools" \
    && yum -y install %PACKAGES% \
    && yum erase epel-release -y \
    && /sbin/scrub.sh

RUN sed -i 's/requiretty/!requiretty/' /etc/sudoers

# setuptools >= 45 and pip>=21 are Python3 only.
RUN pip install --upgrade "pip<21" wheel "virtualenv<20" "setuptools<45"

RUN groupadd -f -g %GID% build
RUN useradd -d /home/build -m -s /bin/bash -u %UID% -g %GID% build
RUN echo "build ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
USER build
