PYTHON   ?= $(shell which python)
WHEELS   ?= $(PWD)/wheelhouse
REQS     ?= $(PWD)/requirements.txt
PIP      ?= $(shell which pip)

.PHONY: pip distribute install

install: distribute pip
	@pip install --use-wheel --no-index --find-links=$(WHEELS) -r $(REQS) wheel
	@cat patches/* | patch -d /opt/zenoss/lib/python2.7/site-packages -p0

pip:
ifeq "$(PIP)" ""
	@wget -qO- https://raw.github.com/pypa/pip/master/contrib/get-pip.py | $(PYTHON)
endif

distribute: pip
	@pip install distribute
